### PR TITLE
fix(watch.js): Fix issues in watch.js

### LINKED ISSUE #15: Bug in watch.js: Doesn't fire if 2 events are less than 1 second apart
Hello,

The algorithm used in [watch.js](https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/watch.js) to handle near events (less than 1 second apart) together, has a bug. Such way the second (and third, fourth, ...) event is (are) not handled at all!

https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/watch.js#L26-L33

This is the first thing in the handler callback (and there is nothing before it):
```js
if (fsWait) return;
```
So the question is simple: What happens when `fsWait` is not falsy? The answer is simple too. The function just returns! And **the event**? Who will handle it? It goes to a [black hole](https://en.wikipedia.org/wiki/Black_hole).

### LINKED ISSUE #16: Bug in watch.js: Shoud check read-access, not just visibility
https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/watch.js#L24

We want to read the file later. So we should check **read-access** (`fs.R_OK`) not just **visibility** (`fs.F_OK`). See https://nodejs.org/api/fs.html#fs_file_access_constants.

### LINKED ISSUE #17: Bug in watch.js: Logs "Watching" before checking file accessibility
`console.log('Watching', path)` should be after we sure the file is accessible. This means it should be a few lines lower, in `if(!err) { ... }` block. Otherwise, the logged message may be incorrect.

https://github.com/madewithkoji/koji-tools/blob/a1ca3c2ec52d5c8321afd128e44978494341df44/watch.js#L21-L25

### PR DESCRIPTION
**Pull request by mirismaili**
fix #15
fix #16
fix #17

### CODE REVIEW

**Comment by sthielen** [comment]
Do you want me to close this and use #20 instead?

**Comment by mirismaili** [comment]
@sthielen 
You are the maintainer and have the choices. I submitted this two separately to you can choose which one is more appropriate.

**Comment by mirismaili** [comment]
I personally prefer #20.

**Comment by mirismaili** [comment]
I added `close #18` keyword into ce305f8 message to close this PR automatically when #20 was merged.

**Pull request merged**
